### ISSUE TITLE
翻译前必读：讨论流程、规范、技巧等等一切问题

### ISSUE THREAD

**Issue by SBeator** [the-road-to-graphql/the-road-to-graphql-chinese#1]
## 翻译前准备

了解GraphQL，推荐大家都阅读一下Robin自己的多篇[关于 GraphQL 的博客](https://www.robinwieruch.de/categories/graphql/)

## 翻译步骤

1. 挑选章节：在相应 Issue 里面回复Mark一下即可（稍后发送[权限 invitation](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/settings/collaboration)）
2. 协调时间/人员：跟你共同翻译的小伙伴协商 tasks 和相应的预估时间
3. fork 项目：clone 至本地进行编辑，推荐 Markdown 编辑器 [Typora](https://www.typora.io/)
4. 翻译：修改你翻译对应的 `*-cn.md` 文件，不要修改不带`-cn`后缀的原始文件（可能用于以后merge最新的英文修改）
5. 提 Pull Request：同时艾特 `@` 同章节的其他翻译小伙伴和做校对的小伙伴
6. Review：直接在 PR 内对应 commits 位置进行评论与讨论
7. 合并：翻译完成

## 翻译的方式

你可以分段将英文和译文放在一起，例如：

```
> The chapter gives you an introduction to React. You may ask yourself: Why should I learn React in the first place? 

本章介绍 React。你可能会问自己：为何应当优先学习 React？
```

这样做的好处：
1. 方便翻译时进行双语对照。
2. 引用符号 `>` 方便翻译完成后一键移除英文（使用正则）
所以用这种方式我们需要两个PR来完成翻译，第一个PR会在文件中每一段后面加上中文，而第二个PR则是移除掉原来的英文部分。

## 翻译的工具有哪些？

- 安利一下好用的 Markdown 编辑器 [Typora](https://www.typora.io/)，功能完备且美观，当然也可以用 Sublime 或者 Intellij 呀，😂
- 可以适当借助 Google 翻译，回过头来看你可能会说，~~卧槽 Google Translate 真是牛逼！~~
- 使用了类似 Trello 的管理工具 [ZenHub](https://www.zenhub.com/)，具备 Pipeline、Estimate、Assignees 等功能，可视化翻译进度。

## 翻译时的常用词汇约定用词规范
| 原文 | 中文 |
| -- | -- |
| command line | 命令行 |
| repository | 代码库 |
| functional stateless components | 无状态组件 |
| terminal | 终端 |
| mount | 挂载 |
| you | 你 |
|Appolo Client| 【无需翻译】|
|Appolo Server| 【无需翻译】|
|API endpoint| 【无需翻译】|
| star| 【无需翻译】|
|query | 查询（操作）|
|mutation| 变更（操作）|
|organization| 组织|
|Exercises | 练习|
| named | 具名， 例如 named query 具名查询 |
| pagination | 分页 |
| interface | 接口 |
| cursor | 游标 |
| meta information | 如果可以很好的意译的话就意译，否则翻译成“元信息（meta information）”  |
| resolver | 解析器  |
| resovler function | 解析函数 |
| model | 模型 |
| following | 如下内容 |
| mutation | 变更(操作) |
| organization | 组织 |
| identifier | 唯一标识 |

## 翻译`练习`的方式

> - Confirm your [source code for the last section](https://github.com/the-road-to-graphql/fullstack-apollo-react-express-boilerplate-project/tree/eeb50f34a2569fa85141bf8ec3f8e9baaf670170)
> - Read more about [Subscriptions with Apollo Server](https://www.apollographql.com/docs/apollo-server/v2/features/subscriptions.html)
> - Watch a talk about [GraphQL Subscriptions](http://youtu.be/bn8qsi8jVew)

- 查看[本节源码](https://github.com/the-road-to-graphql/react-graphql-github-apollo/tree/df737276a4bc8d2d889d182937b77ba9e474e70c)
- 延伸阅读： [Apollo Server 订阅](https://www.apollographql.com/docs/apollo-server/v2/features/subscriptions.html)
- 延伸视频： [GraphQL 订阅](http://youtu.be/bn8qsi8jVew)

## 无需翻译的原则
- 代码中的内容都不翻译（包括在段落中引用代码的内容）
- 大家在中文普通交流都用英文表达的单词，如bug。
- 没有合适的中文对应的专业术语

附不用翻译的词汇列表：
- bug
- Appolo Client
- Appolo Server
- API endpoint
- token相关的内容，如 token,  access token，refresh token, personal token,
- schema  
- issue (作为github issue就不翻译)

## 其他
- 中英文字符之间需要与空格。大家可以用vs code插件 [vscode-pangu](https://marketplace.visualstudio.com/items?itemName=baurine.vscode-pangu) 帮我们快速添加空格
- 一些特殊的不好翻译的词汇不用强行直译，而是可以通过意译的方式让语句通顺

**Comment by SBeator** [comment]
请大家对翻译有任何问题和讨论的，都在这里留言，我们统一好的东西都继续更新在这里

**Comment by reeli** [comment]
repositories

**Comment by LixingSun** [comment]
规范补充：
- star 无需翻译
- query => 查询（操作）
- mutation => 变更（操作）
- organization => 组织
- Exercises => 练习

**Comment by linksgo2011** [comment]
一词多意的情况：

query

- 查询 （查询这个操作或者请求）
- 查询语句

> On the left-hand side of your GraphiQL application, you can fill in GraphQL queries and mutations.

**Comment by linksgo2011** [comment]
用词 补充

- named 具名  例如 named query 具名查询
- pagination 分页
- interface 接口
- cursor 游标
- meta information 元数据？

不翻译

- access token OAuth 访问资源服务器的令牌
