### ISSUE TITLE
需要翻译的各章节文件和行数统计

### ISSUE THREAD

**Issue by SBeator** [the-road-to-graphql/the-road-to-graphql-chinese#12]
| 章节  | 文件 | 文件行数 |
| ------------- | ------------- |-------------|
| [00-foreword](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/tree/master/manuscript/00-foreword) | [00-introduction-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/00-foreword/00-introduction-cn.md) | 14 |
| | [01-about-the-author-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/00-foreword/01-about-the-author-cn.md) | 10 |
| | [02-requirements-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/00-foreword/02-requirements-cn.md) | 30 |
| | [03-faq-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/00-foreword/03-faq-cn.md) | 50 |
| | [04-how-to-read-the-book-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/00-foreword/04-how-to-read-the-book-cn.md) | 16 |
| | [05-challenge-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/00-foreword/05-challenge-cn.md) | 20 |
| [01-graphql](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/tree/master/manuscript/01-graphql) | [index-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/01-graphql/index-cn.md) | 168 |
| [02-apollo](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/tree/master/manuscript/02-apollo) | [index-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/02-apollo/index-cn.md) | 118 |
| [03-graphql-setup](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/tree/master/manuscript/03-graphql-setup) | [index-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/03-graphql-setup/index-cn.md) | 76 |
| [04-graphql-fundamentals](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/tree/master/manuscript/04-graphql-fundamentals) | [index-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/04-graphql-fundamentals/index-cn.md) | 564 |
| [05-graphql-react](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/tree/master/manuscript/05-graphql-react) | [index-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/05-graphql-react/index-cn.md) | 1630 |
| [06-apollo-client](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/tree/master/manuscript/06-apollo-client) | [index-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/06-apollo-client/index-cn.md) | 331 |
| [07-apollo-react](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/tree/master/manuscript/07-apollo-react) | [index-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/07-apollo-react/index-cn.md) | 3709 |
| [08-apollo-server](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/tree/master/manuscript/08-apollo-server) | [index-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/08-apollo-server/index-cn.md) | 5338 |
| [99-end](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/tree/master/manuscript/99-end) | [00-learning-paths-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/99-end/00-learning-paths-cn.md) | 13 |
| | [01-keep-learning-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/99-end/01-keep-learning-cn.md) | 14 |
| | [02-thanks-cn.md](https://github.com/the-road-to-graphql/the-road-to-graphql-chinese/blob/master/manuscript/99-end/02-thanks-cn.md) | 13 |

**Comment by linksgo2011** [comment]
04 占坑
