### ISSUE TITLE
Incorrect link in readme file

### ISSUE THREAD

**Issue by nothingrealhappen** [the-road-to-graphql/the-road-to-graphql-chinese#50]
`这是 [The Road to GraphQL](https://roadtoreact.com/) 的官方仓库（简体中文版）`

The link `https://roadtoreact.com/` is incorrect.

**Comment by scglwsj** [comment]
其实是正确的，作者把自己的好几本书都放到了这个网站里，你要往下滑才能看到这本书。

**Comment by nothingrealhappen** [comment]
好的 受教了 :p
